env:
  browser: true
  es2021: true
plugins:
  - jsx-a11y
  - react
extends:
  - 'eslint:recommended'
  - "plugin:jsx-a11y/recommended"
  - plugin:import/recommended
parserOptions:
  ecmaVersion: 13
  sourceType: module
  ecmaFeatures:
    jsx: true
settings:
  import/ignore:
    - solid-js/web
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  react/jsx-uses-vars:
    - error
  no-unused-vars:
    - 2
    - argsIgnorePattern: "^_"
      varsIgnorePattern: "^_"
  import/extensions:
    - 0
  import/no-unresolved:
    - 0
